# Use the official Python base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the container
COPY . .

# Expose the port that the Flask application will be running on
EXPOSE 5000

# Set the command to run when the container starts
CMD ["python", "app.py"]

# Add the Name and Version labels
LABEL Name=tgsweb
LABEL Version=1.0.0